package com.ojtsu26.elearning.model.enums;

public enum NotificationType {
    FREE_ENROLLMENT_CONFIRMED,
    PAID_ENROLLMENT_ACTIVATED,
    TEACHER_NEW_ENROLLMENT,
    COURSE_COMPLETED,
    COURSE_SUBMITTED_FOR_REVIEW,
    COURSE_APPROVED,
    COURSE_REJECTED,
    COURSE_HIDDEN,
    COURSE_UNHIDDEN,
    PAYMENT_FAILED,
    CERTIFICATE_ISSUED,
    ASSIGNMENT_ASSIGNED,
    ASSIGNMENT_SUBMITTED,
    ASSIGNMENT_GRADED
}
